# Generated by Django 4.2.5 on 2023-10-14 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_contact_alter_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='название')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='адрес')),
                ('content', models.TextField(blank=True, verbose_name='текст')),
                ('preview', models.ImageField(blank=True, upload_to='main/', verbose_name='превью')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('is_published', models.BooleanField(default=False, verbose_name='опубликовано')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='просмотры')),
            ],
            options={
                'verbose_name': 'пост',
                'verbose_name_plural': 'посты',
            },
        ),
    ]
